[package]
name = "libhans-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "*", features = ["derive"] }
serde_repr = "*"
serde = { version = "1.0", features = ["derive"] }
serde_json = "*"
serde_with = "*"
serde-big-array = "0.5.1"
bitflags = "*"
num-traits = "*"
num-derive = "*"
thiserror = "*"
nalgebra = "*"
bincode = "*"
inventory = "*"
colored = "*"

command_derive = { path = "src/command_derive" }
robot_behavior = { path = "crates/robot_behavior" }

[features]
default = ["no_robot"]
no_robot = []
